# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: '*'
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f test-requirements.txt ]; then pip install -r test-requirements.txt; fi
        python setup.py develop
    - name: Test with pytest
      run: |
        git submodule init
        git submodule update --init --recursive
        git submodule update --remote
        pytest tests
    - name: Lint
      run: |
        pip install pylint
        if [ -f .pylintrc.txt ]; then pylint src/dml_project --rcfile .pylintrc; else pylint src/dml_project; fi
        if [ -f tests/.pylintrc.txt ]; then pylint tests --rcfile tests/.pylintrc; else pylint tests; fi
